### ISSUE TITLE
AppVeyor: No Binstar token present?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/eigen-feedstock#3]
Appears that the AppVeyor build failed to [upload packages]( https://ci.appveyor.com/project/conda-forge/eigen-feedstock/build/1.0.3/job/3xve8plkkh63oljv#L1235 ). Not sure what is going on here.

**Comment by ocefpaf** [comment]
This was fixed in the latest conda-smithy. See https://github.com/conda-forge/django-grappelli-feedstock/issues/1

You'll need rerender or wait for another wave of MTN PRs.

**Comment by jakirkham** [comment]
Ok, does this PR ( https://github.com/conda-forge/eigen-feedstock/pull/4 ) fix it?

**Comment by ocefpaf** [comment]
Yes.That should do the trick.
