### ISSUE TITLE
what is the correct eigen include directory?

### ISSUE THREAD

**Issue by beckermr** [conda-forge/eigen-feedstock#37]
In the eigen package I see the headers at `$PREFIX/include/eigen3/Eigen` but some (all?, many?) packages look for `$PREFIX/include/Eigen`. See, for example, pybind11-global. 

What is the correct location and/or how is this usually handled?

**Comment by traversaro** [comment]
As far as I know, Eigen install its headers in `$PREFIX/include/eigen3/Eigen` (see for example the Ubuntu eigen package: https://packages.ubuntu.com/jammy/amd64/libeigen3-dev/filelist) but then downstream projects are supposed to include headers as `#include <Eigen/Core>`. Adding `$PREFIX/include/eigen3` to the include directories is typically done by linking to `Eigen3::Eigen` in CMake or by using the `eigen3` pkg-config.
