### ISSUE TITLE
Eigen 3.4.1 release?

### ISSUE THREAD

**Issue by traversaro** [conda-forge/eigen-feedstock#39]
### Comment:

I saw that we the autotick bot updated Eigen to 3.4.1 . However, I could not find any reference to Eigen 3.4.1 in Eigen website or tags. I just found a 3.4.1 branch, but I am not sure if that is intended to be a release. I will open an issue upstream in Eigen, but anyhow I wanted to open an issue here to track this.

**Comment by traversaro** [comment]
Downstream issue: https://gitlab.com/libeigen/eigen/-/issues/2702 .

**Comment by jcarpent** [comment]
I do agree with @traversaro, there is no official release of Eigen 3.4.1. In addition, this branch is causing compilation errors on upstream projects. I do think this new release on conda-forge should be marked as deprecated or irrelevant.

**Comment by jcarpent** [comment]
Here is the list of all releases: https://gitlab.com/libeigen/eigen/-/releases

**Comment by traversaro** [comment]
Upstream confirmed in https://gitlab.com/libeigen/eigen/-/issues/2702 that 3.4.1 is not a release. I think we should mark 3.4.1 as broken, and remember to avoid using the build number 0 once 3.4.1 actually gets released. I can't easily to a PR to mark Eigen as broken as for a week I only have smartphone access, so if anyone wants to do it it is welcome, thanks! fyi @conda-forge/eigen

**Comment by traversaro** [comment]
As a follow up, the bug that created compilation errors with the "fake" 3.4.1 release was fixed in https://gitlab.com/libeigen/eigen/-/merge_requests/1412, so we should be fine when the "real" 3.4.1 release is released.
