### ISSUE TITLE
Using noarch

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/eigen-feedstock#7]
We probably should look at `noarch` here given they are just headers. I don't want to cause people trouble installing because they want to use them with an unsupported VC for instance.

As I have yet to do this, but have heard murmurings that it is possible. Is this easy to do, @pelson? Are there things we need to watch out for? Are there infrastructure improvements needed?

**Comment by pelson** [comment]
There were a few noarch issues with one of the feedstocks (https://github.com/conda-forge/pyelftools-feedstock/issues/1).

> I don't want to cause people trouble installing because they want to use them with an unsupported VC for instance.

I'm not sure I follow on this. How does ```noarch``` solve the problem?

**Comment by jakirkham** [comment]
> There were a few noarch issues with one of the feedstocks (https://github.com/conda-forge/pyelftools-feedstock/issues/1).

Interesting. Will have a look. Though it appears this wasn't definitively narrowed down to `noarch` as the cause.

> I'm not sure I follow on this. How does ```noarch``` solve the problem?

I think I'm conflating `noarch` with `noarch_python`, which is the confusion here. This package can be used with any VC compiler we want. It is not dependent on a particular OS either so we could go that direction too. This is because it is a header only library.

**Comment by jakirkham** [comment]
Thoughts from others @conda-forge/eigen?

The main downside is we won't run the tests. Though that's really on upstream to do. Don't think there are other, but please correct me if I'm missing some.

All in all this may be a tolerable trade off.

**Comment by jschueller** [comment]
noarch is fine by me

**Comment by jschueller** [comment]
I dont think it can be noarch because of the cmake configurations files, eg EigenConfig.cmake and stuff.
